### ISSUE TITLE
Local development setup

### ISSUE THREAD

**Issue by akphi** [finos/legend-depot#18]
@elopezcastro As discussed before, we are looking for a way to publish entities JARs to a Maven package registry for local development. We picked [Gitlab Package Registry](https://docs.gitlab.com/ee/user/packages/package_registry/) for this purpose as it's out of the box solution. I will spare everyone of the details as to how I configure SDLC to achieve this for now, but I have produced and published the artifacts. This is the link to my registry

https://gitlab.com/api/v4/projects/25339854/packages/maven

And you can see the published JARs here

https://gitlab.com/blacksteed232/myProject/-/packages

I also added you as maintainer of that project so you can tinker around with the project settings - https://gitlab.com/blacksteed232/myProject

I have tried to point to this repo in my `repository-settings.xml` file, but I don't seem to be able to trigger the push from `store-server` to fetch this project metadata. Could you kindly do a test on your end?

```xml
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <localRepository>target/.m2/repository</localRepository>
    <interactiveMode>false</interactiveMode>
    <offline>false</offline>
    <profiles>
        <profile>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <repositories>
                <repository>
                    <id>gitlab-maven</id>
                    <url>https://gitlab.com/api/v4/projects/25339854/packages/maven</url>
                    <layout>default</layout>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                        <updatePolicy>always</updatePolicy>
                    </snapshots>
                </repository>
            </repositories>
        </profile>
    </profiles>
</settings>
```

**Comment by elopezcastro** [comment]
will commit these , there is no reason for the 10mins delay for the queue handler

**Comment by MauricioUyaguari** [comment]
public project test -> https://gitlab.com/finosfoundation/legend/showcase/legend-showcase-project2

**Comment by elopezcastro** [comment]
thanks

here are the use cases:

1. public project : https://gitlab.com/finosfoundation/legend/showcase/legend-showcase-project2
2. private project
3. public group 
4. private group

all of the above need to be set up to publish artifacts :-)

**Comment by MauricioUyaguari** [comment]
Have deployed in the project -> https://gitlab.com/finosfoundation/legend/showcase/legend-showcase-project2/-/packages
and the group -> https://gitlab.com/finosfoundation/legend/showcase/legend-showcase-project2/-/packages

**Comment by elopezcastro** [comment]
can you make a maintainer please for the group

**Comment by MauricioUyaguari** [comment]
Additional testing repos:

- `public` https://gitlab.com/p948 
- `private` https://gitlab.com/groups/privatelegendpipelinepoc/-/packages

**Comment by elopezcastro** [comment]
hi, for the private group the private project coordinates need to be different , they are same as the other project

**Comment by elopezcastro** [comment]
tested for all 4 use cases and works, have committed an example repo settings 

for the private deploy tokens, i will email username/password
